function genQuote() {
  var numQuotes = quotes.length;
  var randNum = Math.floor(Math.random() * numQuotes);
  document.getElementById("quote").innerHTML = quotes[randNum];
  var tweetQuote = quotes[randNum].split(" ").join("%20");
  tweetQuote = tweetQuote.split("<br>").join("");
  tweetQuote =
    "https://twitter.com/intent/tweet?text=Great 1:1 question: " + tweetQuote.split('"').join("");
  $(".twitter-share-button").attr("href", tweetQuote);
}

//questions are from https://getlighthouse.com/blog/one-on-one-meeting-questions-great-managers-ask
var quotes = [
  "How are you? How is life outside of work?",
  "How do you feel your work/life balance is right now?",
  "What is your resentment?",
  "What’s one thing we could change about work for you that would improve your personal life?",
  "If around a holiday: Do you celebrate [Holiday]? How was it?",
  "How are your parents/grandparents? Where do they live? Do you visit them?",
  "If they have children: How is [name of child] doing? (Ask something related to their age like starting school, playing sports, or other interests.)",
  "What do you like to do in your free time? What are your hobbies?",
  "What did you do for fun in the past that you haven’t had as much time for lately?",
  "What drives you? What motivates you to come to work each day?",
  "What work are you doing here that you feel is most in line with your long term goals?",
  "As a kid, what did you want to be when you grew up?",
  "What do you want to be doing in 5 years? 10 years? 3 years?",
  "What are your long term goals? Have you thought about them?",
  "Who do you really admire? Why? (People often admire those they want to become)",
  "If you had millions of dollars, what would you do every day?",
  "What are your super powers? What powers would you like to develop?",
  "What do you want to do in your next job?",
  "Do you feel challenged at work? Are you learning new things?",
  "What area of the company would you like to learn more about?",
  "What skills would you like to develop right now?",
  "Who in the company would you like to learn from? What do you want to learn?",
  "What additional training or education would you like?",
  "Are there any roles in the company you’d like to learn more about?",
  "What do you think are the key skills for your role? How would you rate yourself for each of them?",
  "Do you feel like you’re making progress on your big goals here? Why or why not?",
  "What’s one thing we could do today to help you with your long term goals?",
  "Do you feel we’re helping you advance your career at a pace you would like? Why or why not?",
  "What are your big dreams in life? Are you making progress on them?",
  "Could you see yourself making progress on more of your goals here? What would need to change to do so?",
  "What skills would you like to work on most right now?",
  "Are there any events or training you’d like to attend to help you grow your skills?",
  "Who in the company would you like to learn from? What do you want to learn?",
  "How do you prefer to receive feedback?",
  "Do you feel you’re getting enough feedback? Why/why not?",
  "What’s a recent situation you wish you handled differently? What would you change?",
  "What’s an area of your work you want to improve?",
  "What aspect of your job you would like more help or coaching?",
  "How many hours a day do you feel you’re productive? How could we help you be more productive?",
  "How can I better support you?",
  "What could I do as a manager to make your work easier?",
  "What is something I could do better? What is a criticism you have for me?",
  "What aspects of your work would you like more or less direction from me?",
  "What would you like to know about me?",
  "What could I do to make you enjoy your work more?",
  "What do you like about my management style? What do you dislike?",
  "Is there a situation you’d like my help with?",
  "What have your past managers done that you’d like me to also do or not do?",
  "What’s your favorite thing I do as a manager of this team I should keep doing?",
  "What is the company not doing today that we should do to better compete in the market?",
  "What’s one thing we’d be *crazy* not to do in the next quarter to improve our product?",
  "If you were CEO, what’s the first thing you’d change?",
  "Do you think our company is loyal to its employees? Why or why not?",
  "Are there any aspects of our culture you wish you could change?",
  "What are your favorite parts about our culture?",
  "Which company values do you like the most? Which the least? Why?",
  "What is the #1 Problem at our company? Why?",
  "How could we be more creative or innovative as a company?",
  "How well do you feel like you relate to you coworkers? Do you view them as friends, acquaintances, or strangers?",
  "How could we change our team meetings to be more effective?",
  "What would convince you to leave for a job somewhere else?",
  "Why do you think [employee who recently quit] left? What did they tell you?",
  "Do you feel over-worked, under-worked, or just the right workload?",
  "Do you feel like you’re on the same page with the team? How often do you think you need meetings to ensure you stay that way?",
  "Are there any meetings or discussions you feel you should be a part of that you’re not? Are you included in any you don’t want to be a part of?",
  "Who would you like to work more often with? Why?",
  "Is everyone pulling their weight on the team?",
  "Who is kicking ass on the team? What have they done?",
  "Who on the team do you have the most difficulty working with? Why?",
  "What do you like most about working on our team?",
  "Do you help other members on the team? Do others help you when you need it?",
  "Are you uncomfortable giving any of your peers constructive criticism? If so, why?",
  "What’s an inexpensive thing we could do to improve our office environment for the team?",
  "Is your job what you expected when you accepted it?",
  "What do you feel is your greatest accomplishment here?",
  "When was the time you enjoyed working here the most?",
  "Are you happy with your recent work? Why or why not?",
  "Are you happy working here?",
  "Who are you friends with at work? (Shown to be a key to enjoying your job)",
  "What’s something you feel is undervalued that you contribute to the team?",
  "What part of your job do you wish you didn’t have to do?",
  "What’s not fun about working here? What do you enjoy most about working here?",
  "What worries you? What’s on your mind?",
  "What would make you leave this job for another?"
];